version: "3.8"

services:
  app:
    build: .
    volumes:
      - .:/app/
    ports:
      - 8000:8000
    container_name: inventory_backend
    env_file:
      - ./.env
    depends_on:
      - db

  db:
    image: postgres
    ports:
      - '5432:5432'
    volumes:
      - ./data/db:/home/postgresql/data:rw
    environment:
      - POSTGRES_HOST=db
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    container_name: postgres_db
